In [49]:
import pandas as pd
import numpy as np
import os
from warnings import filterwarnings

filterwarnings('ignore')

In [50]:
data_dict = pd.read_csv(r'../data_dictionary.csv', sep=';') # Data Dictionary

In [51]:
data_dict

Column Name  \
0                                Date   
1                                Time   
2                          Booking ID   
3                      Booking Status   
4                         Customer ID   
5                        Vehicle Type   
6                     Pickup Location   
7                       Drop Location   
8                            Avg VTAT   
9                            Avg CTAT   
10        Cancelled Rides by Customer   
11  Reason for cancelling by Customer   
12          Cancelled Rides by Driver   
13         Driver Cancellation Reason   
14                   Incomplete Rides   
15            Incomplete Rides Reason   
16                      Booking Value   
17                      Ride Distance   
18                     Driver Ratings   
19                    Customer Rating   
20                     Payment Method   

                                          Description  
0                                 Date of the booking  
1                                 Time of the booking  
2             Unique identifier for each ride booking  
3   Status of booking (Completed, Cancelled by Cus...  
4                     Unique identifier for customers  
5   Type of vehicle (Go Mini, Go Sedan, Auto, eBik...  
6                       Starting location of the ride  
7                    Destination location of the ride  
8   Average time for driver to reach pickup locati...  
9   Average trip duration from pickup to destinati...  
10               Customer-initiated cancellation flag  
11                   Reason for customer cancellation  
12                 Driver-initiated cancellation flag  
13                     Reason for driver cancellation  
14                               Incomplete ride flag  
15                        Reason for incomplete rides  
16                     Total fare amount for the ride  
17           Distance covered during the ride (in km)  
18                 Rating given to driver (1-5 scale)  
19               Rating given by customer (1-5 scale)  
20  Method used for payment (UPI, Cash, Credit Car...

In [52]:
df = pd.read_csv(r'../data/raw/uber.csv', sep=',') # Original Dataframe

In [53]:
# for column in df.columns:
#     print(f'Column: {column}\nDtype: {df[column].dtype}\n{df[column].unique()}')

In [54]:
# df

In [55]:
df['Cancelled Rides by Customer'].dtype

dtype('float64')

In [56]:
df[df['Cancelled Rides by Customer'] > 0]['Cancelled Rides by Customer'].unique()

array([1.])

In [57]:
df.dtypes

Date                                  object
Time                                  object
Booking ID                            object
Booking Status                        object
Customer ID                           object
Vehicle Type                          object
Pickup Location                       object
Drop Location                         object
Avg VTAT                             float64
Avg CTAT                             float64
Cancelled Rides by Customer          float64
Reason for cancelling by Customer     object
Cancelled Rides by Driver            float64
Driver Cancellation Reason            object
Incomplete Rides                     float64
Incomplete Rides Reason               object
Booking Value                        float64
Ride Distance                        float64
Driver Ratings                       float64
Customer Rating                      float64
Payment Method                        object
dtype: object

In [58]:
# New dataframe without a few columns

df_clean = df[[
    'Date',
    'Booking Status',
    'Vehicle Type',
    'Avg VTAT',
    'Avg CTAT',
    'Cancelled Rides by Customer',
    'Reason for cancelling by Customer',
    'Cancelled Rides by Driver',
    'Driver Cancellation Reason',
    'Incomplete Rides',
    'Incomplete Rides Reason',
    'Booking Value',
    'Ride Distance',
    'Driver Ratings',
    'Customer Rating',
    'Payment Method'
]]

# df_clean

In [59]:
df_clean.dtypes

Date                                  object
Booking Status                        object
Vehicle Type                          object
Avg VTAT                             float64
Avg CTAT                             float64
Cancelled Rides by Customer          float64
Reason for cancelling by Customer     object
Cancelled Rides by Driver            float64
Driver Cancellation Reason            object
Incomplete Rides                     float64
Incomplete Rides Reason               object
Booking Value                        float64
Ride Distance                        float64
Driver Ratings                       float64
Customer Rating                      float64
Payment Method                        object
dtype: object

In [60]:
df_clean['Date'] = pd.to_datetime(df_clean['Date'])

df_clean.dtypes

Date                                 datetime64[ns]
Booking Status                               object
Vehicle Type                                 object
Avg VTAT                                    float64
Avg CTAT                                    float64
Cancelled Rides by Customer                 float64
Reason for cancelling by Customer            object
Cancelled Rides by Driver                   float64
Driver Cancellation Reason                   object
Incomplete Rides                            float64
Incomplete Rides Reason                      object
Booking Value                               float64
Ride Distance                               float64
Driver Ratings                              float64
Customer Rating                             float64
Payment Method                               object
dtype: object

In [61]:
df_clean['Booking Status'].unique() # No changes needed

array(['No Driver Found', 'Incomplete', 'Completed',
       'Cancelled by Driver', 'Cancelled by Customer'], dtype=object)

In [62]:
df_clean['Vehicle Type'].unique() # No changes needed

array(['eBike', 'Go Sedan', 'Auto', 'Premier Sedan', 'Bike', 'Go Mini',
       'Uber XL'], dtype=object)

In [63]:
df_clean['Avg VTAT'].unique()

array([ nan,  4.9, 13.4, 13.1,  5.3,  5.1,  7.1, 12.1,  6.1,  7.7,  4.6,
       12.2, 14. ,  8.5,  5.6,  6. , 12.4, 10.3,  7. , 10.4,  7.9, 13.6,
       11.5,  3.1,  8.9,  9.2,  2. ,  5.4, 14.6,  6.7,  6.6, 10. , 11. ,
        8. , 12.8,  6.4, 11.3,  2.3,  7.8,  8.8,  9.9,  4.1, 11.2,  3. ,
        9.1,  4.3, 11.4,  6.3, 11.7, 16.6,  5.8,  4. ,  3.4, 11.1,  5.9,
        8.1,  5. , 12. ,  3.2,  9.6,  3.9,  8.4, 10.9,  5.7,  8.6,  9.5,
        2.6,  2.1, 14.4,  7.5, 10.8, 14.7,  3.5,  8.3, 11.9, 12.5, 13.3,
        9.7,  3.6,  9.4,  9. ,  2.4, 19.1,  2.9, 18.5, 16.1, 13.7,  4.5,
        6.9,  6.2,  7.2,  3.7, 11.6,  3.3,  4.7,  7.4,  9.3,  8.2, 13.5,
        4.4,  2.7,  7.3, 10.5,  6.8, 10.7, 12.3,  3.8, 10.2,  9.8,  8.7,
       14.2,  6.5, 12.9,  4.2,  5.2, 16.9,  7.6, 14.9, 11.8, 14.3, 10.1,
       12.6, 14.8, 13.2, 14.5,  4.8, 14.1,  2.5, 15. , 16.2, 12.7,  5.5,
        2.8, 19.2, 18. , 13.9, 13. , 10.6, 20. , 17.6, 15.7,  2.2, 16.5,
       15.9, 19.6, 19.9, 19.8, 16. , 16.4, 13.8, 18

In [64]:
df_clean['Avg VTAT'].dtype

dtype('float64')

In [65]:
df_clean

Date   Booking Status   Vehicle Type  Avg VTAT  Avg CTAT  \
0      2024-03-23  No Driver Found          eBike       NaN       NaN   
1      2024-11-29       Incomplete       Go Sedan       4.9      14.0   
2      2024-08-23        Completed           Auto      13.4      25.8   
3      2024-10-21        Completed  Premier Sedan      13.1      28.5   
4      2024-09-16        Completed           Bike       5.3      19.6   
...           ...              ...            ...       ...       ...   
149995 2024-11-11        Completed        Go Mini      10.2      44.4   
149996 2024-11-24        Completed        Go Mini       5.1      30.8   
149997 2024-09-18        Completed       Go Sedan       2.7      23.4   
149998 2024-10-05        Completed           Auto       6.9      39.6   
149999 2024-03-10        Completed  Premier Sedan       3.5      33.7   

        Cancelled Rides by Customer Reason for cancelling by Customer  \
0                               NaN                               NaN   
1                               NaN                               NaN   
2                               NaN                               NaN   
3                               NaN                               NaN   
4                               NaN                               NaN   
...                             ...                               ...   
149995                          NaN                               NaN   
149996                          NaN                               NaN   
149997                          NaN                               NaN   
149998                          NaN                               NaN   
149999                          NaN                               NaN   

        Cancelled Rides by Driver Driver Cancellation Reason  \
0                             NaN                        NaN   
1                             NaN                        NaN   
2                             NaN                        NaN   
3                             NaN                        NaN   
4                             NaN                        NaN   
...                           ...                        ...   
149995                        NaN                        NaN   
149996                        NaN                        NaN   
149997                        NaN                        NaN   
149998                        NaN                        NaN   
149999                        NaN                        NaN   

        Incomplete Rides Incomplete Rides Reason  Booking Value  \
0                    NaN                     NaN            NaN   
1                    1.0       Vehicle Breakdown          237.0   
2                    NaN                     NaN          627.0   
3                    NaN                     NaN          416.0   
4                    NaN                     NaN          737.0   
...                  ...                     ...            ...   
149995               NaN                     NaN          475.0   
149996               NaN                     NaN         1093.0   
149997               NaN                     NaN          852.0   
149998               NaN                     NaN          333.0   
149999               NaN                     NaN          806.0   

        Ride Distance  Driver Ratings  Customer Rating Payment Method  
0                 NaN             NaN              NaN            NaN  
1                5.73             NaN              NaN            UPI  
2               13.58             4.9              4.9     Debit Card  
3               34.02             4.6              5.0            UPI  
4               48.21             4.1              4.3            UPI  
...               ...             ...              ...            ...  
149995          40.08             3.7              4.1    Uber Wallet  
149996          21.31             4.8              5.0            UPI  
149997          15.93             3.9

In [66]:
# Transforming float flag columns in bool

In [67]:
'''
Column: Cancelled Rides by Customer
Dtype: float64 (flag)
Has NaN

Column: Cancelled Rides by Driver
Dtype: float64 (flag)
Has NaN

Column: Incomplete Rides
Dtype: float64 (flag)
Has NaN
''';

In [68]:
df.columns

Index(['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID',
       'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT',
       'Avg CTAT', 'Cancelled Rides by Customer',
       'Reason for cancelling by Customer', 'Cancelled Rides by Driver',
       'Driver Cancellation Reason', 'Incomplete Rides',
       'Incomplete Rides Reason', 'Booking Value', 'Ride Distance',
       'Driver Ratings', 'Customer Rating', 'Payment Method'],
      dtype='object')

In [69]:
df_clean

Date   Booking Status   Vehicle Type  Avg VTAT  Avg CTAT  \
0      2024-03-23  No Driver Found          eBike       NaN       NaN   
1      2024-11-29       Incomplete       Go Sedan       4.9      14.0   
2      2024-08-23        Completed           Auto      13.4      25.8   
3      2024-10-21        Completed  Premier Sedan      13.1      28.5   
4      2024-09-16        Completed           Bike       5.3      19.6   
...           ...              ...            ...       ...       ...   
149995 2024-11-11        Completed        Go Mini      10.2      44.4   
149996 2024-11-24        Completed        Go Mini       5.1      30.8   
149997 2024-09-18        Completed       Go Sedan       2.7      23.4   
149998 2024-10-05        Completed           Auto       6.9      39.6   
149999 2024-03-10        Completed  Premier Sedan       3.5      33.7   

        Cancelled Rides by Customer Reason for cancelling by Customer  \
0                               NaN                               NaN   
1                               NaN                               NaN   
2                               NaN                               NaN   
3                               NaN                               NaN   
4                               NaN                               NaN   
...                             ...                               ...   
149995                          NaN                               NaN   
149996                          NaN                               NaN   
149997                          NaN                               NaN   
149998                          NaN                               NaN   
149999                          NaN                               NaN   

        Cancelled Rides by Driver Driver Cancellation Reason  \
0                             NaN                        NaN   
1                             NaN                        NaN   
2                             NaN                        NaN   
3                             NaN                        NaN   
4                             NaN                        NaN   
...                           ...                        ...   
149995                        NaN                        NaN   
149996                        NaN                        NaN   
149997                        NaN                        NaN   
149998                        NaN                        NaN   
149999                        NaN                        NaN   

        Incomplete Rides Incomplete Rides Reason  Booking Value  \
0                    NaN                     NaN            NaN   
1                    1.0       Vehicle Breakdown          237.0   
2                    NaN                     NaN          627.0   
3                    NaN                     NaN          416.0   
4                    NaN                     NaN          737.0   
...                  ...                     ...            ...   
149995               NaN                     NaN          475.0   
149996               NaN                     NaN         1093.0   
149997               NaN                     NaN          852.0   
149998               NaN                     NaN          333.0   
149999               NaN                     NaN          806.0   

        Ride Distance  Driver Ratings  Customer Rating Payment Method  
0                 NaN             NaN              NaN            NaN  
1                5.73             NaN              NaN            UPI  
2               13.58             4.9              4.9     Debit Card  
3               34.02             4.6              5.0            UPI  
4               48.21             4.1              4.3            UPI  
...               ...             ...              ...            ...  
149995          40.08             3.7              4.1    Uber Wallet  
149996          21.31             4.8              5.0            UPI  
149997          15.93             3.9

In [70]:
df_clean['Cancelled Rides by Customer'].unique()

array([nan,  1.])

In [71]:
df_clean['Cancelled Rides by Customer'] = df_clean['Cancelled Rides by Customer'].fillna(0).astype('int')

In [72]:
df_clean['Cancelled Rides by Customer'].unique()

array([0, 1])

In [73]:
df_clean['Cancelled Rides by Driver'].unique()

array([nan,  1.])

In [74]:
df_clean['Cancelled Rides by Driver'] = df_clean['Cancelled Rides by Driver'].fillna(0).astype('int')

In [75]:
df_clean['Cancelled Rides by Driver'].unique()

array([0, 1])

In [76]:
df_clean['Incomplete Rides'].unique()

array([nan,  1.])

In [77]:
df_clean['Incomplete Rides'] = df_clean['Incomplete Rides'].fillna(0).astype('int')

In [78]:
df_clean['Incomplete Rides'].unique()

array([0, 1])

In [79]:
df_clean.dtypes

Date                                 datetime64[ns]
Booking Status                               object
Vehicle Type                                 object
Avg VTAT                                    float64
Avg CTAT                                    float64
Cancelled Rides by Customer                   int64
Reason for cancelling by Customer            object
Cancelled Rides by Driver                     int64
Driver Cancellation Reason                   object
Incomplete Rides                              int64
Incomplete Rides Reason                      object
Booking Value                               float64
Ride Distance                               float64
Driver Ratings                              float64
Customer Rating                             float64
Payment Method                               object
dtype: object

In [80]:
# Transforming conditional fields

In [81]:
'''
Column: Reason for cancelling by Customer
Dtype: object
Has NaN

Column: Driver Cancellation Reason
Dtype: object
Has NaN

Column: Incomplete Rides Reason
Dtype: object
Has NaN
''';

In [82]:
df_clean['Reason for cancelling by Customer'].unique()

array([nan, 'Driver is not moving towards pickup location',
       'Driver asked to cancel', 'AC is not working', 'Change of plans',
       'Wrong Address'], dtype=object)

In [83]:
df_clean['Reason for cancelling by Customer'] = df_clean['Reason for cancelling by Customer'].fillna('N/A')

In [84]:
df_clean['Reason for cancelling by Customer'].unique()

array(['N/A', 'Driver is not moving towards pickup location',
       'Driver asked to cancel', 'AC is not working', 'Change of plans',
       'Wrong Address'], dtype=object)

In [85]:
df_clean['Driver Cancellation Reason'] = df_clean['Driver Cancellation Reason'].fillna('N/A')

In [86]:
df_clean['Driver Cancellation Reason'].unique()

array(['N/A', 'Personal & Car related issues', 'Customer related issue',
       'More than permitted people in there',
       'The customer was coughing/sick'], dtype=object)

In [87]:
df_clean['Incomplete Rides Reason'] = df_clean['Incomplete Rides Reason'].fillna('N/A')

In [88]:
df_clean['Incomplete Rides Reason'].unique()

array(['N/A', 'Vehicle Breakdown', 'Other Issue', 'Customer Demand'],
      dtype=object)

In [89]:
df_clean['Payment Method'] = df_clean['Payment Method'].fillna('N/A')

In [90]:
df_clean['Payment Method'].unique()

array(['N/A', 'UPI', 'Debit Card', 'Cash', 'Uber Wallet', 'Credit Card'],
      dtype=object)

In [91]:
len(df_clean[df_clean['Avg VTAT'].isna()])

10500

In [92]:
df_clean.dtypes

Date                                 datetime64[ns]
Booking Status                               object
Vehicle Type                                 object
Avg VTAT                                    float64
Avg CTAT                                    float64
Cancelled Rides by Customer                   int64
Reason for cancelling by Customer            object
Cancelled Rides by Driver                     int64
Driver Cancellation Reason                   object
Incomplete Rides                              int64
Incomplete Rides Reason                      object
Booking Value                               float64
Ride Distance                               float64
Driver Ratings                              float64
Customer Rating                             float64
Payment Method                               object
dtype: object

In [93]:
# for column in df_clean.columns:
#     print(f'Column: {column}\nDtype: {df[column].dtype}\n{df[column].unique()}')

In [94]:
if os.path.exists(r'../data/processed/uber_clean.csv'):
    print(f'File already exists in: {r"../data/processed/uber_clean.csv"}')
else:
    df_clean.to_csv(r'../data/processed/uber_clean.csv', index=False)
    print(f'csv file saved successfully.')

csv file saved successfully.
